start: 2020121418
end: 2021011312
step: PT6H
experiment: ufoeval
cdump: gdas
resolution: c768
forecast_steps: [PT3H, PT4H, PT5H, PT6H, PT7H, PT8H, PT9H]
forecast_files:
    - coupler.res
    - fv_core.res
    - fv_srf_wnd.res
    - fv_tracer.res
    - phy_data
    - sfc_data
tiles: [1, 2, 3, 4, 5, 6]
fc_root: /Users/rmahajan/scratch/Data/c768_v15ics_v16tag
stage: /Users/rmahajan/scratch/Test/r2d2
user_date_format: '%Y%m%d.%H%M%S'
fc_date_rendering: 'analysis'
database: local
