start: 2016100300
end: 2016100300
step: PT6H
experiment: fv3_control
cdump: gdas
resolution: c192
forecast_steps: [PT6H, PT12H, PT18H, PT24H, PT30H, PT36H, PT42H, PT48H, PT54H, PT60H, PT66H, PT72H, PT78H]
forecast_files:
    - coupler.res
    - fv_core.res
    - fv_srf_wnd.res
    - fv_tracer.res
    - phy_data
    - sfc_data
tiles: [1, 2, 3, 4, 5, 6]
fc_root: /work/noaa/da/rmahajan/work/UFS/standalone/stmp/RESTART
stage: /work/noaa/marine/Jian.Kuang/jcsda/r2d2-test
user_date_format: '%Y%m%d.%H%M%S'
fc_date_rendering: 'analysis'
database: local
